### ISSUE TITLE
Feature request address generate from public key

### ISSUE THREAD

**Issue by crossle** [chuwt/chia-client#1]

**Comment by chuwt** [comment]
由于Go没有clvm，所以通过公钥生成地址(puzzle_hash)这块暂时还不太好实现，目前也只能像生成离线交易一样，通过Python代码提供一个本地socket服务，传入私钥返回地址。有时间我研究下这块代码，看看能否根据python代码把这块单独hack成Go代码

**Comment by chuwt** [comment]
Hey @crossle, https://github.com/chuwt/chia-address-generator 实现了功能，可以试一下，欢迎PR和Issues
